version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:18.04
    parallelism: 4
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            circleci tests split versions.txt | xargs -I RV -n 1 make -e R_VERSION=RV build
  push:
    docker:
      - image: circleci/buildpack-deps:18.04
    parallelism: 4
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            docker login --username ${DOCKERHUB_USER} --password ${DOCKERHUB_PASS}
            circleci tests split versions.txt | xargs -I RV -n 1 make -e R_VERSION=RV push
workflows:
  version: 2
  build-and-push:
    jobs:
      - build:
          context: dockerhub
      - push:
          requires:
            - build
          context: dockerhub
